# Generated by Django 5.0.2 on 2024-10-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('max_attempts', models.IntegerField(default=1000)),
            ],
        ),
    ]
