# Generated by Django 5.0.2 on 2024-11-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_cracked_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
