# Generated by Django 5.0.2 on 2024-11-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_requirements',
        ),
    ]
