# Generated by Django 5.0.2 on 2024-11-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_password_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_requirements',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
